<a href="https://colab.research.google.com/github/Raju057/ML-Models-/blob/main/Copy_of_Copy_of_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

In [3]:
a=np.arange(15).reshape(3,5)

In [4]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [5]:
a.ndim

2

In [6]:
a.shape

(3, 5)

In [7]:
a.dtype

dtype('int64')

In [8]:
a.size

15

In [9]:
a.resize(5,3)

In [10]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [11]:
a.ndim

2

Array Creation

*   array from a regular Python list or tuple using the array function. 
*   array transforms sequences of sequences into two-dimensional arrays, sequences of sequences of sequences into three dimensional
arrays, and so on.


 

In [12]:
import numpy as np
a = np.array([2,3,4])
a

array([2, 3, 4])

In [13]:
a.dtype

dtype('int64')

In [14]:
v=np.array(([2,3],[5,6]))

In [15]:
v

array([[2, 3],
       [5, 6]])

In [16]:
v.shape


(2, 2)


*   The function **zeros** creates an array full of zeros
*   function **ones** creates an array full of ones
* function **empty** creates an array whose initial content is random and depends on the state of the memory. 
*  By default, the dtype of the created array is float64, but it can be specified via the key word argument dtype.


In [17]:
b=np.ones((2,3,2))
b

array([[[1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.]]])

In [18]:
a=np.zeros((2,3),dtype=np.int16)
a

array([[0, 0, 0],
       [0, 0, 0]], dtype=int16)

**arange** : To create sequences of numbers, NumPy provides the **arange** function which is analogous to the Python built-in range,
but returns an array.

In [19]:
b=np.arange(10,30,5)
b

array([10, 15, 20, 25])

In [20]:
a=np.arange(1,20,2)
a

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [21]:
c=np.arange(2.0,10.0,0.5)
c

array([2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. ,
       8.5, 9. , 9.5])

**linspace** :
When arange is used with floating point arguments, it is generally not possible to predict the number of elements
obtained, due to the finite floating point precision. For this reason, it is usually better to use the function **linspace** that
receives as an argument the number of elements that we want, 

In [22]:
a=np.linspace(0.2,5,9)
a


array([0.2, 0.8, 1.4, 2. , 2.6, 3.2, 3.8, 4.4, 5. ])

In [23]:
b=np.linspace(1,5,10).round(2)
b

array([1.  , 1.44, 1.89, 2.33, 2.78, 3.22, 3.67, 4.11, 4.56, 5.  ])

Printing Arrays

In [24]:
a = np.arange(6) # 1D array
a

array([0, 1, 2, 3, 4, 5])

In [25]:
b=np.arange(12).reshape(3,4) #2d array
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [26]:
from numpy.core.fromnumeric import shape
shape(b)

(3, 4)

In [27]:
b.size

12

In [29]:
c=np.arange(24).reshape(2,3,4) #3d array
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

Basic Operations:Arithmetic operators on arrays apply elementwise. A new array is created and filled with the result.

In [30]:
a=np.array([10,20,30,40])
b=np.array([2,6,8,10])

In [32]:
c = a+b
c

array([12, 26, 38, 50])

In [33]:
d=a-b
d

array([ 8, 14, 22, 30])

In [34]:
e = a**b
e

array([              100,          64000000,      656100000000,
       10485760000000000])

In [36]:
a<20

array([ True, False, False, False])

In [41]:
a=np.array([[1,1],[0,1]])
b=np.array([[2,0],[3,4]])

In [42]:
a*b # product operator * operates elementwise in NumPy arrays

array([[2, 0],
       [0, 4]])

In [43]:
a@b #The matrix product can be performed using the @ operator 

array([[5, 4],
       [3, 4]])

In [50]:
b=np.array([[2,0],[3,4]]) #another matrix product

h=a.dot(b)

In [51]:
h

array([[5, 4],
       [3, 4]])